version: "3.9"

services:
  tempo:
    image: grafana/tempo:2.7.2
    container_name: tempo
    command:
      - -config.file=/etc/tempo/tempo.yml
    ports:
      - "3200:3200"
    volumes:
      - ./observability-stack/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./observability-stack/loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:v1.7.5
    container_name: alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./observability-stack/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - alloy_data:/var/lib/alloy/data
    depends_on:
      - loki
    networks:
      - monitoring

  api:
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo:4318/v1/traces

  dependency:
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo:4318/v1/traces

volumes:
  loki_data: {}
  alloy_data: {}
  tempo_data: {}
