groups:
  - name: basic
    rules:
      - alert: PrometheusTargetDown
        expr: up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "A target is down"
          description: "Target {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
